
GET http://localhost:3000/todos/

###
POST http://localhost:3000/todos/
Content-Type:application/json

{ "id":1,
  "date":"2024-07-28",
  "description": "saving money",
  "amount": 5000,
  "transactionType":"credit"
}

###
POST http://localhost:3000/todos/
Content-Type:application/json

{
  "id":1,
  "date":"2024-07-28",
  "description": "saving money",
  "amount": 5000,
  "transactionType":"debit"
}

###

PUT http://localhost:3000/todos//
Content-Type:application/json

{ "debit": 1500 }

###
DELETE http://localhost:3000/todos/1/