
GET http://localhost:3000/todos/

###
POST http://localhost:3000/todos/
Content-Type:application/json

{ "id":3,
  "date":"2024-07-28",
  "description": "saving money",
  "credit": 0,
  "debit":300
  
}

###

PUT http://localhost:3000/todos//
Content-Type:application/json

{ "debit": 1500 }

###
DELETE http://localhost:3000/todos/1/