
GET http://localhost:3000/todos/

###
POST http://localhost:3000/todos/
Content-Type:application/json

{
  "date":"2024-07-28",
  "description": "saving money",
  "credit": 5000,
  "debit":0
}

###
POST http://localhost:3000/todos/
Content-Type:application/json

{
  "date":"28-07-2024",
  "description": "room rent",
  "credit": 0,
  "debit": 25
}

###

PUT http://localhost:3000/todos//
Content-Type:application/json

{ "debit": 1500 }

###
DELETE http://localhost:3000/todos/2/